const Grade = {
	position: [
		{ "title": "사원", "code": "POS001" },
		{ "title": "주임", "code": "POS002" },
		{ "title": "계장", "code": "POS003" },
		{ "title": "대리", "code": "POS004" },
		{ "title": "과장", "code": "POS005" },
		{ "title": "차장", "code": "POS006" },
		{ "title": "부장", "code": "POS007" },
		{ "title": "책임매니저", "code": "POS008" },
		{ "title": "매니저", "code": "POS009" },
		{ "title": "임원", "code": "POS010" },
		{ "title": "감사", "code": "POS011" },
		{ "title": "이사", "code": "POS012" },
		{ "title": "상무", "code": "POS013" },
		{ "title": "전무", "code": "POS014" },
		{ "title": "부사장", "code": "POS015" },
		{ "title": "사장", "code": "POS016" },
		{ "title": "연구원", "code": "POS017" },
		{ "title": "주임연구원", "code": "POS018" },
		{ "title": "선임연구원", "code": "POS019" },
		{ "title": "책임연구원", "code": "POS020" },
		{ "title": "수석연구원", "code": "POS021" },
		{ "title": "연구소장", "code": "POS022" },
		{ "title": "면접후결정", "code": "POS023" }
	],
	responsibilitie: [
		{ "title": "팀원", "code": "RES001" },
		{ "title": "팀장", "code": "RES002" },
		{ "title": "실장", "code": "RES003" },
		{ "title": "총무", "code": "RES004" },
		{ "title": "지점장", "code": "RES005" },
		{ "title": "지사장", "code": "RES006" },
		{ "title": "파트장", "code": "RES007" },
		{ "title": "그룹장", "code": "RES008" },
		{ "title": "센터장", "code": "RES009" },
		{ "title": "책임매니저", "code": "RES010" },
		{ "title": "매니저", "code": "RES011" },
		{ "title": "본부장", "code": "RES012" },
		{ "title": "사업부장", "code": "RES013" },
		{ "title": "원장", "code": "RES014" },
		{ "title": "국장", "code": "RES015" },
	]
}
export default Grade